import Head from 'next/head';
// import 'bootstrap/dist/css/bootstrap.min.css';
import Hero from '../components/Hero';
import styles from '../styles/layout/Home.module.scss'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
    </>
  )
}
