import Head from "next/head";
import Hero from "../components/Hero";
import styles from "../styles/layout/Home.module.scss";
import NavbarMain from "../components/Navbar";
import CardList from "../components/CardList/CardList";
import Jumbo from "../components/Jumbo"
import Footer from "../components/Footer";
import { useState, useEffect } from "react";
import LoadingBar from 'react-top-loading-bar'

const Home = () => {

  const [progress, setProgress] = useState(0);
  const [overlay, setOverlay] = useState(false);
  const [cartListLength, setCartListLength] = useState(0);


  useEffect( () => {
    setProgress(100)
  }, [])

  useEffect(() => {
    const cartList = [...JSON.parse(localStorage.getItem("cartList"))];
    setCartListLength(cartList.length);
  }, [])

  return (
    <div className={styles.Home}>
      <Head>
        <title>Journaly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <LoadingBar
        color='#ff800b'
        progress={progress}
        onLoaderFinished={() =>{ setProgress(0), setOverlay(true)}}
      />

      {
        !overlay ? <div className="overlay"></div>
        : 
        <div></div>
      }
      
      <Hero />
      <NavbarMain cartQty={cartListLength}/>
      <Jumbo/>
      <CardList list={"cities"} title={"Top rated cities"} className="top_rated" />
      <CardList list={"experiences"} title={"Top experiences"} className="top_experiences" />
      <Footer />
    </div>
  );
};

export default Home;
