import Head from 'next/head';
import Hero from '../components/Hero';
import styles from '../styles/layout/Home.module.scss'
import Navbar from '../components/Navbar'
import CardList from '../components/CardList/CardList'
import Image from 'next/image';


const Home = () => {
  return (
    <div className={styles.Home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Hero />
      <Navbar/>
      <CardList list={"cities"} />
      <CardList list={"experiences"} />
    </div>
  )
}


export default Home;